global using DataCore.Data;
global using DataCore.Models;
global using Microsoft.EntityFrameworkCore;
global using MobileStoreV2.DatabaseSeeder.Classes;
global using Microsoft.Extensions.Logging;
global using MudBlazor.Services;
global using DataCore.Services.Interfaces;
global using DataCore.Services;
global using MobileStoreV2.DatabaseSeeder;
